<style>
.text-center{
	text-align:center;
}
.apply-margin{
	margin-top:15px;
}
.align-left{
	float:left;
}
.align-right{
	float:right;
}
.size-of-font{
	font-size:18px;
}
.apply-pad-right{
	padding-right:15px;
}
.apply-pad-left{
	padding-left:15px;
}
.apply-pad-top{
	padding-top:20px;
}
.apply-pad-bottom{
padding-bottom:20px;
}
.bgcolor{
	background-color: #bfc9ca;
}
.font-shade{
	font-weight:bold;
}
</style>
<h1 class="apply-margin size-of-font apply-pad-top apply-pad-bottom bgcolor font-shade"><p class="align-left apply-pad-left">WORLD OF E-Commerce</p><p class="align-right apply-pad-right">Welcome Shruti!!!!!!!!!!!!!! </p></h1>
<!--<h3 class="align-right size-of-font">Welcome Shruti!!!!!!!!!!!!!!</h3>-->
